### PR TITLE
React version simplified and optimized

### PR DESCRIPTION
**Pull request by darkxeno**
PS: Would be interesting if for the next tests we can have a more real example to tweak.

PS2: Angular 2 times are impressive specially on update times. I have saw 3 interesting things by the way related with angular 2 times:

1 - The differences in time between the first render and the following ones are big
2 - The render times to generate the rows changes drastically to worse if we omit the reset step of the test, is like rendering 2 times the same gives worse results, React get better results in this case because of the virtual dom recycling
3 - (conjecture) Some Angular 2 optimizations seems to 'survive' the removal of the elements on the DOM, that would explain point 1 and maybe affect point 2.

### CODE REVIEW

**Comment by ShMcK** [comment]
Thanks again for your contributions.

Any suggestions for a 'more real example'?

**Comment by darkxeno** [comment]
The problem is that the 2 only very consuming tasks that be measured on his
performance can be big lists and html games. Maybe we can try to has a more
real list, more styled and with images and more data. Maybe a fake list of
tweets (or other similar simple content) that mixes some realtime updates
on the content (times for example - X seconds ago ) with realtime data
feeding served from the meteor websocket. But of course all in a easy way.

By the way, i had discovered yesterday part of optimization magic behind
angular 2, the usage of the html template tag, in fact i made a version
working with react 0.14 beta that add this feature and times changed so
much. Now the 50000 items render is more fast in React than on Angular 2
but the updates keeps being more fast in Angular 2.

If you want i can make you a pull request, but the problem is that this
time, to use the React version 0.14 beta, i needed to use webpack for the
build, but i can add only the builded file if you want to test it.

2015-08-31 11:25 GMT+02:00 ShMcK notifications@github.com:

**Comment by ShMcK** [comment]
I would have assumed the template tag would make things slower, due to the extra shadow-dom rendering. Note that the template tag is also used in Blaze.

Actually, I tried running tests to see if component/template rendering made a difference. For example, one app that loads nested components compared to a single component doing the same thing. The results were about the same.

In order to make a fair test for the front-end we'd have to control the backend and as many variables as possible. If the tests are run by loading data from external sources, the main limiting factor will be the variable speed of fetching and receiving those sources. It's already very hard to draw any conclusions. Running a test provides different results at different times on different machines in different browsers, etc.

I would like to see the results for React 0.14, to see what has changed from 0.13.

**Comment by darkxeno** [comment]
This why i mention fake data. We can send for example:

On ms 0 - 1000 rows
On ms 100 - 100 updates on the previous rows
On ms 200ms - another 1000 rows
On ms 300ms - deletions for 500 random rows
After that finished - some click events load that changes things on the rows
...

If we see that some parts can no be done properly we can remove it, but i
am trying to have all the thing that normally a website can support.

The data and timings will be the same between runs.

Suppossing than the test framework can measure all that.

**Comment by ShMcK** [comment]
As opposed to pre-loading all data as in the example?
I'm not sure the results would be much different.

You can run this very simply by forking the repo and editing the server files. I'm curious about the results.

**Pull request merged**
